# By Hasnain Malek
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
# Get X state management to home 
  get: ^4.6.6
# Cupertino Icons style
  cupertino_icons: ^1.0.6
# For api call
  http: ^1.1.2
# For converting CSV data to List
  csv: ^5.1.1
# for lottie animation 
  lottie: ^3.0.0
# for storing data (in local storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
# for integrating ads
  google_mobile_ads: ^4.0.0
#for initializing firebase 
  # firebase_core: ^2.25.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/